// Almacén global de posts para compartir entre APIs
export interface Post {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  author: string;
  isAutoGenerated?: boolean;
  source?: string;
  model?: string;
  confidence?: number;
}

// Posts en memoria para producción
let globalPosts: Post[] = [
  {
    id: '1',
    title: 'Bienvenido a nuestro blog inteligente',
    category: 'Technology',
    content: 'Este es el primer post de nuestro blog alimentado por IA. Aquí compartiremos contenido interesante sobre tecnología, viajes, comida, moda y cultura. Nuestro sistema de inteligencia artificial genera contenido automáticamente todos los días a las 9:00 AM, asegurando que siempre tengas algo nuevo e interesante que leer.',
    createdAt: new Date().toISOString(),
    author: 'Blog Admin',
    isAutoGenerated: false
  },
  {
    id: '2',
    title: 'La revolución de la inteligencia artificial en 2025',
    category: 'Technology',
    content: 'La inteligencia artificial está transformando la manera en que vivimos, trabajamos y nos relacionamos. En 2025, estamos viendo avances extraordinarios en áreas como el procesamiento de lenguaje natural, la visión por computadora y la automatización de procesos. Estas tecnologías están democratizando el acceso a herramientas poderosas que antes estaban reservadas para grandes corporaciones.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    author: 'AI Content Bot',
    isAutoGenerated: true,
    source: 'AI Mock Generator',
    model: 'Local AI System',
    confidence: 0.85
  },
  {
    id: '3',
    title: 'Destinos de viaje que están marcando tendencia',
    category: 'Travel',
    content: 'El mundo del turismo está experimentando una transformación fascinante. Los viajeros modernos buscan experiencias más auténticas y sostenibles. Desde las playas vírgenes de Indonesia hasta los pueblos remotos de los Andes, los destinos emergentes están captando la atención de aventureros de todo el mundo.',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    author: 'AI Content Bot',
    isAutoGenerated: true,
    source: 'AI Mock Generator',
    model: 'Local AI System',
    confidence: 0.78
  }
];

export class PostStore {
  static getAllPosts(): Post[] {
    return [...globalPosts];
  }

  static addPost(post: Post): void {
    globalPosts.unshift(post);
    
    // Mantener solo los últimos 50 posts
    if (globalPosts.length > 50) {
      globalPosts = globalPosts.slice(0, 50);
    }
  }

  static getPostById(id: string): Post | undefined {
    return globalPosts.find(post => post.id === id);
  }

  static getPostsByCategory(category: string): Post[] {
    return globalPosts.filter(post => post.category === category);
  }

  static getLatestPost(): Post | undefined {
    return globalPosts[0];
  }

  static getAutoGeneratedPosts(): Post[] {
    return globalPosts.filter(post => post.isAutoGenerated);
  }

  static getLastAutoGeneratedPost(): Post | undefined {
    return globalPosts.find(post => post.isAutoGenerated);
  }
}
