'use client';

import React, { useState, useEffect } from 'react';
import styles from './featured.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

interface Post {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  author: string;
  isAutoGenerated?: boolean;
  media?: {
    type: 'image' | 'video';
    url: string;
    filename: string;
    size: number;
    mimeType: string;
  };
}

// Función para obtener el último post
async function getLatestPost(): Promise<Post | null> {
  const latestPosts = await PostStore.getLatestPosts(1);
  return latestPosts.length > 0 ? latestPosts[0] : null;
}

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'Technology': '/style.png',
    'Travel': '/travel.png',
    'Food': '/food.png',
    'Fashion': '/fashion.png',
    'Culture': '/culture.png',
    'Coding': '/coding.png'
  };
  return categoryImages[category] || '/p1.jpeg';
}

// Función para truncar el contenido
function truncateContent(content: string, maxLength: number = 200): string {
  if (content.length <= maxLength) return content;
  return content.substring(0, maxLength) + '...';
}

const Featured: React.FC = () => {
  const [latestPost, setLatestPost] = useState<Post | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadLatestPost = async () => {
      try {
        setLoading(true);
        const post = await getLatestPost();
        setLatestPost(post);
      } catch (error) {
        console.error('Error loading latest post:', error);
      } finally {
        setLoading(false);
      }
    };

    loadLatestPost();
  }, []);

  if (loading) {
    return (
      <div className={styles.container}>
        <h1 className={styles.title}>
          <b>Recent Posts</b> Lo más nuevo en nuestro blog
        </h1>
        <div className={styles.post}>
          <div className={styles.loading}>
            <p>Cargando post reciente...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <h1 className={styles.title}>
        <b>Recent Posts</b> Lo más nuevo en nuestro blog
      </h1>
      <div className={styles.post}>
        <div className={styles.imgContainer}>
          {latestPost?.media && latestPost.media.type === 'image' ? (
            <Image 
              src={latestPost.media.url} 
              alt={latestPost.title} 
              fill 
              className={styles.image} 
            />
          ) : latestPost?.media && latestPost.media.type === 'video' ? (
            <video 
              src={latestPost.media.url} 
              className={styles.video}
              controls={false}
              muted
              playsInline
            />
          ) : (
            <Image 
              src={latestPost ? getCategoryImage(latestPost.category) : '/p1.jpeg'} 
              alt="featured post" 
              fill 
              className={styles.image} 
            />
          )}
        </div>
        <div className={styles.textContainer}>
          {latestPost ? (
            <>
              <div className={styles.postMeta}>
                <span className={styles.category}>{latestPost.category}</span>
                {latestPost.isAutoGenerated && (
                  <span className={styles.aiTag}>🤖 AI Generated</span>
                )}
              </div>
              <h1 className={styles.postTitle}>{latestPost.title}</h1>
              <p className={styles.postDesc}>
                {truncateContent(latestPost.content)}
              </p>
              <Link href={`/posts/${latestPost.id}`}>
                <button className={styles.button}>Read More</button>
              </Link>
            </>
          ) : (
            <>
              <h1 className={styles.postTitle}>¡Bienvenido a nuestro blog!</h1>
              <p className={styles.postDesc}>
                Aquí encontrarás contenido interesante sobre tecnología, viajes, comida, moda y cultura. 
                Nuestro sistema de IA genera contenido automáticamente todos los días.
              </p>
              <Link href="/admin">
                <button className={styles.button}>Generar Contenido</button>
              </Link>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default Featured;
