import { NextRequest, NextResponse } from 'next/server';
import { writeFile, readFile } from 'fs/promises';
import path from 'path';
import { PostStore, Post } from '@/lib/postStore';

const POSTS_FILE = path.join(process.cwd(), 'data', 'posts.json');

// Crear archivo de posts si no existe
async function ensurePostsFile() {
  try {
    await readFile(POSTS_FILE, 'utf8');
  } catch (error) {
    // Si el archivo no existe, crear uno vacío
    const dataDir = path.dirname(POSTS_FILE);
    await writeFile(dataDir, '', { flag: 'a' }).catch(() => {});
    await writeFile(POSTS_FILE, JSON.stringify([]));
  }
}

export async function POST(request: NextRequest) {
  try {
    const { title, category, content, author, isAutoGenerated } = await request.json();

    if (!title || !category || !content) {
      return NextResponse.json(
        { error: 'Título, categoría y contenido son requeridos' },
        { status: 400 }
      );
    }

    // Crear nuevo post
    const newPost: Post = {
      id: Date.now().toString(),
      title,
      category,
      content,
      createdAt: new Date().toISOString(),
      author: author || 'Admin',
      isAutoGenerated: isAutoGenerated || false
    };

    // En producción, usar almacén global
    if (process.env.NODE_ENV === 'production') {
      PostStore.addPost(newPost);
      return NextResponse.json({
        message: 'Post creado exitosamente',
        post: newPost,
        success: true
      });
    }

    // En desarrollo, usar archivo
    await ensurePostsFile();
    const postsData = await readFile(POSTS_FILE, 'utf8');
    const posts: Post[] = JSON.parse(postsData);

    // Agregar el nuevo post
    posts.unshift(newPost);

    // Guardar posts actualizados
    await writeFile(POSTS_FILE, JSON.stringify(posts, null, 2));

    return NextResponse.json({
      message: 'Post creado exitosamente',
      post: newPost,
      success: true
    });

  } catch (error) {
    console.error('Error saving post:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    // En producción, usar almacén global
    if (process.env.NODE_ENV === 'production') {
      return NextResponse.json({
        posts: PostStore.getAllPosts(),
        success: true
      });
    }
    
    // En desarrollo, usar archivo
    await ensurePostsFile();
    const postsData = await readFile(POSTS_FILE, 'utf8');
    const posts: Post[] = JSON.parse(postsData);

    return NextResponse.json({
      posts,
      success: true
    });

  } catch (error) {
    console.error('Error reading posts:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}
