import { NextRequest, NextResponse } from 'next/server';
import { writeFile, readFile } from 'fs/promises';
import path from 'path';

interface Post {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  author: string;
  isAutoGenerated?: boolean;
}

const POSTS_FILE = path.join(process.cwd(), 'data', 'posts.json');

// Posts en memoria para producción
let inMemoryPosts: Post[] = [
  {
    id: '1',
    title: 'Bienvenido a nuestro blog inteligente',
    category: 'Technology',
    content: 'Este es el primer post de nuestro blog alimentado por IA. Aquí compartiremos contenido interesante sobre tecnología, viajes, comida, moda y cultura. Nuestro sistema de inteligencia artificial genera contenido automáticamente todos los días a las 9:00 AM, asegurando que siempre tengas algo nuevo e interesante que leer.',
    createdAt: new Date().toISOString(),
    author: 'Blog Admin',
    isAutoGenerated: false
  },
  {
    id: '2',
    title: 'La revolución de la inteligencia artificial en 2025',
    category: 'Technology',
    content: 'La inteligencia artificial está transformando la manera en que vivimos, trabajamos y nos relacionamos. En 2025, estamos viendo avances extraordinarios en áreas como el procesamiento de lenguaje natural, la visión por computadora y la automatización de procesos. Estas tecnologías están democratizando el acceso a herramientas poderosas que antes estaban reservadas para grandes corporaciones.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    author: 'AI Content Bot',
    isAutoGenerated: true
  },
  {
    id: '3',
    title: 'Destinos de viaje que están marcando tendencia',
    category: 'Travel',
    content: 'El mundo del turismo está experimentando una transformación fascinante. Los viajeros modernos buscan experiencias más auténticas y sostenibles. Desde las playas vírgenes de Indonesia hasta los pueblos remotos de los Andes, los destinos emergentes están captando la atención de aventureros de todo el mundo.',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    author: 'AI Content Bot',
    isAutoGenerated: true
  }
];

// Crear archivo de posts si no existe
async function ensurePostsFile() {
  try {
    await readFile(POSTS_FILE, 'utf8');
  } catch (error) {
    // Si el archivo no existe, crear uno vacío
    const dataDir = path.dirname(POSTS_FILE);
    await writeFile(dataDir, '', { flag: 'a' }).catch(() => {});
    await writeFile(POSTS_FILE, JSON.stringify([]));
  }
}

export async function POST(request: NextRequest) {
  try {
    const { title, category, content } = await request.json();

    if (!title || !category || !content) {
      return NextResponse.json(
        { error: 'Título, categoría y contenido son requeridos' },
        { status: 400 }
      );
    }

    // Crear nuevo post
    const newPost: Post = {
      id: Date.now().toString(),
      title,
      category,
      content,
      createdAt: new Date().toISOString(),
      author: 'Admin', // Puedes cambiar esto por el usuario actual
      isAutoGenerated: false
    };

    // En producción, usar posts en memoria
    if (process.env.NODE_ENV === 'production') {
      inMemoryPosts.unshift(newPost);
      return NextResponse.json({
        message: 'Post creado exitosamente',
        post: newPost,
        success: true
      });
    }

    // En desarrollo, usar archivo
    await ensurePostsFile();
    const postsData = await readFile(POSTS_FILE, 'utf8');
    const posts: Post[] = JSON.parse(postsData);

    // Agregar el nuevo post
    posts.unshift(newPost);

    // Guardar posts actualizados
    await writeFile(POSTS_FILE, JSON.stringify(posts, null, 2));

    return NextResponse.json({
      message: 'Post creado exitosamente',
      post: newPost,
      success: true
    });

  } catch (error) {
    console.error('Error saving post:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    // En producción, usar posts en memoria
    if (process.env.NODE_ENV === 'production') {
      return NextResponse.json({
        posts: inMemoryPosts,
        success: true
      });
    }
    
    // En desarrollo, usar archivo
    await ensurePostsFile();
    const postsData = await readFile(POSTS_FILE, 'utf8');
    const posts: Post[] = JSON.parse(postsData);

    return NextResponse.json({
      posts,
      success: true
    });

  } catch (error) {
    console.error('Error reading posts:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}
