import React from 'react';
import styles from './page.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

interface CategoryPageProps {
  params: {
    category: string;
  };
}

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'technology': '/style.png',
    'travel': '/travel.png',
    'food': '/food.png',
    'fashion': '/fashion.png',
    'culture': '/culture.png',
    'coding': '/coding.png'
  };
  return categoryImages[category.toLowerCase()] || '/p1.jpeg';
}

// Función para formatear la fecha
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

// Función para capitalizar la primera letra
function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export default async function CategoryPage({ params }: CategoryPageProps) {
  const categoryName = decodeURIComponent(params.category);
  const posts = await PostStore.getPostsByCategory(capitalizeFirst(categoryName));

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <div className={styles.headerContent}>
          <div className={styles.categoryInfo}>
            <h1 className={styles.title}>Categoría: {capitalizeFirst(categoryName)}</h1>
            <p className={styles.description}>
              Explora todos nuestros artículos de {categoryName.toLowerCase()}. 
              Contenido curado y generado por IA para mantenerte siempre actualizado.
            </p>
            <div className={styles.stats}>
              <span className={styles.postCount}>{posts.length} artículos disponibles</span>
            </div>
          </div>
          <div className={styles.categoryImage}>
            <Image 
              src={getCategoryImage(categoryName)} 
              alt={categoryName}
              fill 
              className={styles.image} 
            />
          </div>
        </div>
      </div>

      <div className={styles.content}>
        {posts.length === 0 ? (
          <div className={styles.noPosts}>
            <h2>No hay posts en esta categoría</h2>
            <p>Pronto tendremos contenido interesante sobre {categoryName.toLowerCase()}.</p>
            <Link href="/" className={styles.backHome}>← Volver al inicio</Link>
          </div>
        ) : (
          <div className={styles.postsGrid}>
            {posts.map((post) => (
              <Link href={`/posts/${post.id}`} key={post.id} className={styles.postCard}>
                <div className={styles.cardImage}>
                  <Image 
                    src={getCategoryImage(post.category)} 
                    alt={post.category}
                    fill 
                    className={styles.cardImg} 
                  />
                  {post.isAutoGenerated && (
                    <div className={styles.aiTag}>🤖 IA</div>
                  )}
                </div>
                <div className={styles.cardContent}>
                  <div className={styles.cardMeta}>
                    <span className={styles.cardDate}>{formatDate(post.createdAt)}</span>
                    <span className={styles.cardAuthor}>{post.author}</span>
                  </div>
                  <h3 className={styles.cardTitle}>{post.title}</h3>
                  <p className={styles.cardExcerpt}>
                    {post.content.substring(0, 150)}...
                  </p>
                  <div className={styles.readMore}>
                    Leer más →
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
      
      <div className={styles.navigation}>
        <Link href="/" className={styles.navButton}>← Inicio</Link>
        <Link href="/posts" className={styles.navButton}>Todos los posts</Link>
      </div>
    </div>
  );
}
