'use client';

import React, { useState, useEffect } from 'react';
import styles from './page.module.css';
import Image from 'next/image';
import { PostStore } from '@/lib/postStore';

interface PostPageProps {
  params: {
    id: string;
  };
}

interface Post {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  author: string;
  isAutoGenerated?: boolean;
  source?: string;
  model?: string;
  confidence?: number;
  likes?: number;
  media?: {
    type: 'image' | 'video';
    url: string;
    filename: string;
    size: number;
    mimeType: string;
  };
}

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'Technology': '/style.png',
    'Travel': '/travel.png',
    'Food': '/food.png',
    'Fashion': '/fashion.png',
    'Culture': '/culture.png',
    'Coding': '/coding.png'
  };
  return categoryImages[category] || '/p1.jpeg';
}

// Función para formatear la fecha
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}

export default function PostPage({ params }: PostPageProps) {
  const [post, setPost] = useState<Post | null>(null);
  const [loading, setLoading] = useState(true);
  const [likes, setLikes] = useState(0);
  const [hasLiked, setHasLiked] = useState(false);

  useEffect(() => {
    const loadPost = async () => {
      try {
        setLoading(true);
        const postData = await PostStore.getPostById(params.id);
        setPost(postData || null);
        setLikes(postData?.likes || 0);
      } catch (error) {
        console.error('Error loading post:', error);
      } finally {
        setLoading(false);
      }
    };

    loadPost();
  }, [params.id]);

  const handleLike = async () => {
    if (post && !hasLiked) {
      const success = await PostStore.likePost(post.id);
      if (success) {
        setLikes(likes + 1);
        setHasLiked(true);
      }
    }
  };

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.loading}>
          <h1>Cargando post...</h1>
        </div>
      </div>
    );
  }

  if (!post) {
    return (
      <div className={styles.container}>
        <div className={styles.notFound}>
          <h1>Post no encontrado</h1>
          <p>El post que buscas no existe o ha sido eliminado.</p>
          <a href="/" className={styles.backLink}>← Volver al inicio</a>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.infoContainer}>
        <div className={styles.textContainer}>
          <h1 className={styles.title}>{post.title}</h1>
          <div className={styles.meta}>
            <span className={styles.category}>{post.category}</span>
            <span className={styles.date}>{formatDate(post.createdAt)}</span>
            <span className={styles.author}>Por {post.author}</span>
            {post.isAutoGenerated && (
              <span className={styles.aiTag}>🤖 Generado por IA</span>
            )}
          </div>
        </div>
        <div className={styles.imageContainer}>
          {post.media && post.media.type === 'image' ? (
            <Image 
              src={post.media.url} 
              alt={post.title}
              fill 
              className={styles.image} 
            />
          ) : post.media && post.media.type === 'video' ? (
            <video 
              src={post.media.url} 
              className={styles.video}
              controls
              playsInline
            />
          ) : (
            <Image 
              src={getCategoryImage(post.category)} 
              alt={post.category}
              fill 
              className={styles.image} 
            />
          )}
        </div>
      </div>
      
      <div className={styles.content}>
        <div className={styles.contentText}>
          {post.content.split('\n\n').map((paragraph, index) => (
            <p key={index} className={styles.paragraph}>
              {paragraph}
            </p>
          ))}
        </div>
        
        {post.isAutoGenerated && (
          <div className={styles.aiInfo}>
            <h3>🤖 Información de generación automática</h3>
            <div className={styles.aiDetails}>
              <p><strong>Fuente:</strong> {post.source || 'No especificado'}</p>
              <p><strong>Modelo:</strong> {post.model || 'No especificado'}</p>
              <p><strong>Confianza:</strong> {((post.confidence || 0) * 100).toFixed(1)}%</p>
            </div>
          </div>
        )}
        
        <div className={styles.likesSection}>
          <button 
            onClick={handleLike} 
            className={`${styles.likeButton} ${hasLiked ? styles.liked : ''}`}
            disabled={hasLiked}
          >
            👍 {likes} Me gusta
          </button>
          <span className={styles.likeText}>
            {hasLiked ? '¡Gracias por tu like!' : 'Si te gustó este post, dale me gusta'}
          </span>
        </div>
        
        <div className={styles.actions}>
          <a href="/" className={styles.backButton}>← Volver al inicio</a>
          <a href="/posts" className={styles.allPostsButton}>Ver todos los posts</a>
        </div>
      </div>
    </div>
  );
}
