'use client';

import React, { useState, useEffect } from 'react';
import styles from './page.module.css';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

export default function WritePage() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [loading, setLoading] = useState(true);
  const [formData, setFormData] = useState({
    title: '',
    category: 'Technology',
    content: '',
    media: null as {
      type: 'image' | 'video';
      url: string;
      filename: string;
      size: number;
      mimeType: string;
    } | null,
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null);
  const [createdPostId, setCreatedPostId] = useState<string | null>(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);
  const router = useRouter();

  const categories = [
    'Technology',
    'Travel', 
    'Food',
    'Fashion',
    'Culture',
    'Coding'
  ];

  useEffect(() => {
    // Verificar autenticación
    const authData = localStorage.getItem('blogAuth');
    if (!authData) {
      router.push('/login');
      return;
    }
    
    try {
      JSON.parse(authData);
      setIsAuthenticated(true);
    } catch (error) {
      localStorage.removeItem('blogAuth');
      router.push('/login');
      return;
    }
    
    setLoading(false);
  }, [router]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    setUploadProgress(0);

    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Error al subir el archivo');
      }

      const result = await response.json();
      
      setFormData(prev => ({
        ...prev,
        media: result.file
      }));

      setMessage({
        type: 'success',
        text: `Archivo subido exitosamente: ${result.file.originalName}`
      });

    } catch (error: any) {
      setMessage({
        type: 'error',
        text: error.message || 'Error al subir el archivo'
      });
    } finally {
      setIsUploading(false);
      setUploadProgress(0);
    }
  };

  const removeMedia = () => {
    setFormData(prev => ({
      ...prev,
      media: null
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setMessage(null);
    setCreatedPostId(null);

    try {
      // Crear el post directamente en PostStore (ahora con base de datos)
      const newPost = {
        id: Date.now().toString(),
        title: formData.title,
        category: formData.category,
        content: formData.content,
        createdAt: new Date().toISOString(),
        author: 'Admin User',
        isAutoGenerated: false,
        likes: 0,
        media: formData.media
      };

      // Agregar al PostStore (ahora guarda en MongoDB)
      await PostStore.addPost(newPost);

      setCreatedPostId(newPost.id);
      setMessage({
        type: 'success',
        text: '¡Post creado exitosamente y guardado en la base de datos! 🎉'
      });

      // Limpiar formulario
      setFormData({
        title: '',
        category: 'Technology',
        content: '',
        media: null,
      });

    } catch (error: any) {
      setMessage({
        type: 'error',
        text: error.message || 'Error al crear el post'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.loading}>
          <h2>Verificando autenticación...</h2>
        </div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return null;
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>✍️ Escribir Nuevo Post</h1>
        <p className={styles.subtitle}>
          Crea contenido personalizado para tu blog
        </p>
      </div>

      <div className={styles.formContainer}>
        <form onSubmit={handleSubmit} className={styles.form}>
          <div className={styles.inputGroup}>
            <label htmlFor="title" className={styles.label}>
              Título del Post
            </label>
            <input
              type="text"
              id="title"
              name="title"
              value={formData.title}
              onChange={handleInputChange}
              className={styles.input}
              placeholder="Escribe un título atractivo..."
              required
            />
          </div>

          <div className={styles.inputGroup}>
            <label htmlFor="category" className={styles.label}>
              Categoría
            </label>
            <select
              id="category"
              name="category"
              value={formData.category}
              onChange={handleInputChange}
              className={styles.select}
              required
            >
              {categories.map(category => (
                <option key={category} value={category}>
                  {category}
                </option>
              ))}
            </select>
          </div>

          <div className={styles.inputGroup}>
            <label htmlFor="content" className={styles.label}>
              Contenido
            </label>
            <textarea
              id="content"
              name="content"
              value={formData.content}
              onChange={handleInputChange}
              className={styles.textarea}
              placeholder="Escribe el contenido de tu post aquí..."
              rows={12}
              required
            />
            <div className={styles.charCount}>
              {formData.content.length} caracteres
            </div>
          </div>

          <div className={styles.inputGroup}>
            <label htmlFor="media" className={styles.label}>
              Imagen o Video (opcional)
            </label>
            <input
              type="file"
              id="media"
              name="media"
              accept="image/*,video/*"
              onChange={handleFileUpload}
              className={styles.fileInput}
            />
            {uploadProgress > 0 && uploadProgress < 100 && (
              <div className={styles.progressContainer}>
                <div className={styles.progressBar}>
                  <div 
                    className={styles.progressFill} 
                    style={{ width: `${uploadProgress}%` }}
                  ></div>
                </div>
                <span className={styles.progressText}>{uploadProgress}%</span>
              </div>
            )}
            {formData.media && (
              <div className={styles.mediaPreview}>
                <p>📎 Archivo seleccionado: {formData.media.filename}</p>
                <p>📏 Tamaño: {(formData.media.size / 1024 / 1024).toFixed(2)} MB</p>
                <p>🎯 Tipo: {formData.media.type}</p>
                <button 
                  type="button" 
                  onClick={removeMedia}
                  className={styles.removeButton}
                >
                  🗑️ Eliminar archivo
                </button>
              </div>
            )}
          </div>

          {message && (
            <div className={`${styles.message} ${styles[message.type]}`}>
              {message.text}
              {message.type === 'success' && createdPostId && (
                <div className={styles.viewPostContainer}>
                  <button
                    onClick={() => router.push(`/posts/${createdPostId}`)}
                    className={styles.viewPostButton}
                  >
                    👁️ Ver Post
                  </button>
                </div>
              )}
            </div>
          )}

          <div className={styles.actions}>
            <Link href="/admin" className={styles.cancelButton}>
              Cancelar
            </Link>
            <button 
              type="submit" 
              className={styles.submitButton}
              disabled={isSubmitting}
            >
              {isSubmitting ? 'Publicando...' : 'Publicar Post'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
