'use client';

import React, { useState, useEffect } from 'react';
import styles from './page.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

// Interfaz para el tipo de post
interface Post {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  author: string;
  isAutoGenerated?: boolean;
  likes?: number;
  media?: {
    type: 'image' | 'video';
    url: string;
    filename: string;
    size: number;
    mimeType: string;
  };
}

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'Technology': '/style.png',
    'Travel': '/travel.png',
    'Food': '/food.png',
    'Fashion': '/fashion.png',
    'Culture': '/culture.png',
    'Coding': '/coding.png'
  };
  return categoryImages[category] || '/p1.jpeg';
}

// Función para formatear la fecha
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

export default function PostsPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadPosts = async () => {
      try {
        setLoading(true);
        const allPosts = await PostStore.getAllPosts();
        setPosts(allPosts);
        setError(null);
      } catch (err) {
        setError('Error al cargar los posts');
        console.error('Error loading posts:', err);
      } finally {
        setLoading(false);
      }
    };

    loadPosts();
  }, []);

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.header}>
          <h1 className={styles.title}>Cargando Artículos...</h1>
          <p className={styles.description}>
            Por favor espera mientras cargamos el contenido.
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.container}>
        <div className={styles.header}>
          <h1 className={styles.title}>Error</h1>
          <p className={styles.description}>{error}</p>
          <Link href="/" className={styles.backHome}>← Volver al inicio</Link>
        </div>
      </div>
    );
  }

  const categories = Array.from(new Set(posts.map(post => post.category)));

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>Todos los Artículos</h1>
        <p className={styles.description}>
          Explora nuestra colección completa de artículos sobre tecnología, viajes, 
          comida, moda y cultura. Contenido fresco generado automáticamente por IA.
        </p>
        <div className={styles.stats}>
          <span className={styles.totalPosts}>{posts.length} artículos total</span>
          <span className={styles.aiPosts}>
            {posts.filter(p => p.isAutoGenerated).length} generados por IA
          </span>
        </div>
      </div>

      <div className={styles.filters}>
        <h3>Filtrar por categoría:</h3>
        <div className={styles.categoryFilters}>
          <Link href="/posts" className={styles.filterButton}>
            Todas ({posts.length})
          </Link>
          {categories.map(category => {
            const categoryPosts = posts.filter(p => p.category === category);
            return (
              <Link 
                key={category} 
                href={`/blog/${category.toLowerCase()}`} 
                className={styles.filterButton}
              >
                {category} ({categoryPosts.length})
              </Link>
            );
          })}
        </div>
      </div>

      <div className={styles.postsGrid}>
        {posts.map((post) => (
          <Link href={`/posts/${post.id}`} key={post.id} className={styles.postCard}>
            <div className={styles.cardImage}>
              {post.media && post.media.type === 'image' ? (
                <Image 
                  src={post.media.url} 
                  alt={post.title}
                  fill 
                  className={styles.cardImg} 
                />
              ) : post.media && post.media.type === 'video' ? (
                <video 
                  src={post.media.url} 
                  className={styles.cardVideo}
                  controls={false}
                  muted
                  playsInline
                />
              ) : (
                <Image 
                  src={getCategoryImage(post.category)} 
                  alt={post.category}
                  fill 
                  className={styles.cardImg} 
                />
              )}
              {post.isAutoGenerated && (
                <div className={styles.aiTag}>🤖 Generado por IA</div>
              )}
            </div>
            <div className={styles.cardContent}>
              <div className={styles.cardMeta}>
                <span className={styles.category}>{post.category}</span>
                <span className={styles.date}>{formatDate(post.createdAt)}</span>
              </div>
              <h3 className={styles.cardTitle}>{post.title}</h3>
              <p className={styles.cardExcerpt}>
                {post.content.substring(0, 150)}...
              </p>
              <div className={styles.cardFooter}>
                <span className={styles.author}>Por {post.author}</span>
                <span className={styles.readMore}>Leer más →</span>
              </div>
            </div>
          </Link>
        ))}
      </div>

      {posts.length === 0 && (
        <div className={styles.noPosts}>
          <h2>No hay posts disponibles</h2>
          <p>Pronto tendremos contenido interesante para ti.</p>
          <Link href="/" className={styles.backHome}>← Volver al inicio</Link>
        </div>
      )}
      
      <div className={styles.navigation}>
        <Link href="/" className={styles.navButton}>← Volver al inicio</Link>
        <Link href="/admin" className={styles.navButton}>Panel Admin</Link>
      </div>
    </div>
  );
}
