import React from 'react';
import styles from './page.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'Technology': '/style.png',
    'Travel': '/travel.png',
    'Food': '/food.png',
    'Fashion': '/fashion.png',
    'Culture': '/culture.png',
    'Coding': '/coding.png'
  };
  return categoryImages[category] || '/p1.jpeg';
}

// Función para formatear la fecha
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

export default function PostsPage() {
  const posts = PostStore.getAllPosts();
  const categories = Array.from(new Set(posts.map(post => post.category)));

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>Todos los Artículos</h1>
        <p className={styles.description}>
          Explora nuestra colección completa de artículos sobre tecnología, viajes, 
          comida, moda y cultura. Contenido fresco generado automáticamente por IA.
        </p>
        <div className={styles.stats}>
          <span className={styles.totalPosts}>{posts.length} artículos total</span>
          <span className={styles.aiPosts}>
            {posts.filter(p => p.isAutoGenerated).length} generados por IA
          </span>
        </div>
      </div>

      <div className={styles.filters}>
        <h3>Filtrar por categoría:</h3>
        <div className={styles.categoryFilters}>
          <Link href="/posts" className={styles.filterButton}>
            Todas ({posts.length})
          </Link>
          {categories.map(category => {
            const categoryPosts = posts.filter(p => p.category === category);
            return (
              <Link 
                key={category} 
                href={`/blog/${category.toLowerCase()}`} 
                className={styles.filterButton}
              >
                {category} ({categoryPosts.length})
              </Link>
            );
          })}
        </div>
      </div>

      <div className={styles.postsGrid}>
        {posts.map((post) => (
          <Link href={`/posts/${post.id}`} key={post.id} className={styles.postCard}>
            <div className={styles.cardImage}>
              <Image 
                src={getCategoryImage(post.category)} 
                alt={post.category}
                fill 
                className={styles.cardImg} 
              />
              {post.isAutoGenerated && (
                <div className={styles.aiTag}>🤖 Generado por IA</div>
              )}
            </div>
            <div className={styles.cardContent}>
              <div className={styles.cardMeta}>
                <span className={styles.category}>{post.category}</span>
                <span className={styles.date}>{formatDate(post.createdAt)}</span>
              </div>
              <h3 className={styles.cardTitle}>{post.title}</h3>
              <p className={styles.cardExcerpt}>
                {post.content.substring(0, 150)}...
              </p>
              <div className={styles.cardFooter}>
                <span className={styles.author}>Por {post.author}</span>
                <span className={styles.readMore}>Leer más →</span>
              </div>
            </div>
          </Link>
        ))}
      </div>

      {posts.length === 0 && (
        <div className={styles.noPosts}>
          <h2>No hay posts disponibles</h2>
          <p>Pronto tendremos contenido interesante para ti.</p>
          <Link href="/" className={styles.backHome}>← Volver al inicio</Link>
        </div>
      )}
      
      <div className={styles.navigation}>
        <Link href="/" className={styles.navButton}>← Volver al inicio</Link>
        <Link href="/admin" className={styles.navButton}>Panel Admin</Link>
      </div>
    </div>
  );
}
