'use client';

import React, { useState } from 'react';
import styles from './page.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { PostStore } from '@/lib/postStore';

// Función para obtener la imagen de categoría
function getCategoryImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    'Technology': '/style.png',
    'Travel': '/travel.png',
    'Food': '/food.png',
    'Fashion': '/fashion.png',
    'Culture': '/culture.png',
    'Coding': '/coding.png'
  };
  return categoryImages[category] || '/p1.jpeg';
}

// Función para formatear la fecha
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

export default function BlogPage() {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  
  const categories = ['All', 'Technology', 'Travel', 'Food', 'Fashion', 'Culture'];
  
  const handleCategoryChange = (category: string) => {
    setSelectedCategory(category);
  };

  const filteredPosts = selectedCategory === 'All' 
    ? PostStore.getAllPosts() 
    : PostStore.getPostsByCategory(selectedCategory);

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>Blog</h1>
        <p className={styles.subtitle}>
          Descubre nuestro contenido sobre las últimas tendencias y desarrollos
        </p>
      </div>
      
      <div className={styles.filters}>
        <h2>Filtrar por categoría</h2>
        <div className={styles.categoryButtons}>
          {categories.map((category) => (
            <button
              key={category}
              className={`${styles.categoryButton} ${
                selectedCategory === category ? styles.active : ''
              }`}
              onClick={() => handleCategoryChange(category)}
            >
              {category === 'All' ? 'Todas' : category}
            </button>
          ))}
        </div>
      </div>

      <div className={styles.stats}>
        <div className={styles.stat}>
          <span className={styles.statNumber}>{filteredPosts.length}</span>
          <span className={styles.statLabel}>
            {selectedCategory === 'All' ? 'Total de posts' : `Posts en ${selectedCategory}`}
          </span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statNumber}>{categories.length - 1}</span>
          <span className={styles.statLabel}>Categorías</span>
        </div>
      </div>

      <div className={styles.content}>
        {filteredPosts.length > 0 ? (
          <div className={styles.postGrid}>
            {filteredPosts.map((post) => (
              <div key={post.id} className={styles.postCard}>
                <div className={styles.imageContainer}>
                  <Image 
                    src={getCategoryImage(post.category)} 
                    alt={post.category}
                    fill
                    className={styles.image}
                  />
                </div>
                <div className={styles.textContainer}>
                  <div className={styles.detail}>
                    <span className={styles.date}>{formatDate(post.createdAt)}</span>
                    <span className={styles.category}>{post.category}</span>
                  </div>
                  <Link href={`/posts/${post.id}`} className={styles.link}>
                    <h3 className={styles.postTitle}>{post.title}</h3>
                  </Link>
                  <p className={styles.desc}>
                    {post.content.substring(0, 200)}...
                  </p>
                  <div className={styles.author}>
                    <span>Por {post.author}</span>
                    {post.isAutoGenerated && (
                      <span className={styles.aiTag}>🤖 IA</span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className={styles.noPosts}>
            <h3>No hay posts disponibles en esta categoría</h3>
            <p>Pronto agregaremos más contenido. ¡Vuelve pronto!</p>
          </div>
        )}
      </div>
    </div>
  );
}
